# Generated by Django 5.2.14 on 2026-07-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_medication"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bmi",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "BMI",
                "verbose_name_plural": "BMI",
            },
        ),
        migrations.AlterModelOptions(
            name="headcircumference",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "Head Circumference",
                "verbose_name_plural": "Head Circumference",
            },
        ),
        migrations.AlterModelOptions(
            name="height",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "Height",
                "verbose_name_plural": "Height",
            },
        ),
        migrations.AlterModelOptions(
            name="weight",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "Weight",
                "verbose_name_plural": "Weight",
            },
        ),
    ]
