# Generated by Django 5.2.15 on 2026-09-25 10:18

import core.models
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_merge_0037_alter_options_0039_sleep_wakeups"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Saved dish",
                "verbose_name_plural": "Saved dishes",
                "ordering": [django.db.models.functions.text.Lower("name")],
            },
        ),
        migrations.AddField(
            model_name="meal",
            name="dish_names",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[core.models.validate_dish_names],
                verbose_name="Saved dishes",
            ),
        ),
        migrations.CreateModel(
            name="DishFood",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.dish"
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.food"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dish",
            name="foods",
            field=models.ManyToManyField(
                through="core.DishFood", to="core.food", verbose_name="Foods"
            ),
        ),
        migrations.AddConstraint(
            model_name="dishfood",
            constraint=models.UniqueConstraint(
                fields=("dish", "food"), name="core_dish_food_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="dish",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="core_dish_name_ci_unique",
            ),
        ),
    ]
